image: maven:3-jdk-11
before_script:
  - apt-get update -qq && apt-get install

services:
  - mysql:latest
  - mongo:latest

connect:
  stage: database_setup_mysql
  image: mysql:latest
  script:
    - echo "
      CREATE SCHEMA IF NOT EXISTS gipher;
      USE gipher;
      CREATE TABLE IF NOT EXISTS `gipher`.`user` (
      `user_id` INT NOT NULL AUTO_INCREMENT,
      `username` VARCHAR(45) NOT NULL,
      `password` VARCHAR(256) NOT NULL,
      `photo` VARCHAR(256) NULL,
      PRIMARY KEY (`user_id`)
      );
      CREATE USER IF NOT EXISTS "gipher"@"mysql" IDENTIFIED BY "password";
      GRANT ALL PRIVILEGES ON gipher.* TO "mysql"@"localhost";" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"


cache:
  key: "maven3"
  paths:
    - .m2/repository

variables:
  SONAR_URL: "http://jenkins-immersive.stackroute.in:9000/"
  SONAR_LOGIN: "admin"
  SONAR_PASSWORD: "admin"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MYSQL_DATABASE: "gipher"
  MYSQL_ROOT_PASSWORD: "admin"

stages:
  - database_setup_mysql
  - build
  - test
  - package
  - test_quality

maven_job:
  stage: build
  script:
    - mvn clean install

maven_build:
  stage: package
  script: mvn clean package
  artifacts:
    paths:
      - /target/*.jar

code_coverage:
  stage: test
  script:
    - "mvn clean test"
    - "mvn jacoco:report"
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/",instructions, "instructions covered"; print 100*covered/instructions, "% covered" }'
  coverage: '/Code coverage: \d+\.\d+/'
  artifacts:
    paths:
      - target/site/jacoco/



