version: "3"

services:
  favoriteservicedb:
    image: mongo:latest
    container_name: favoriteservicedb
    volumes:
      - favoriteservicedata:/data/db
    ports:
      - 27017:27017
  springboot-eureka-server:
    image: springboot-eureka-server:1.0
    container_name: eurekaserver
    ports:
      - 8761:8761
    environment:
      eureka.instance.hostname: springboot-eureka-server
      eureka.client.serviceUrl.defaultZone: http://springboot-eureka-server:8761/eureka
  userservicedb:
    image: mysql:8.0
    container_name: userservicedb
    environment:
      MYSQL_DATABASE: gipher
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3307:3306
    volumes:
      - userservice-mysql-data:/var/lib/mysql

  springboot-userservice:
    image: springboot-userservice:1.0
    container_name: userservice
    ports:
      - 9999:9999
    expose:
      - 9999
    environment:
      eureka.client.serviceUrl.defaultZone: http://springboot-eureka-server:8761/eureka
    depends_on:
      - userservicedb

  springboot-spring-cloud-gateway:
    image: springboot-spring-cloud-gateway:1.0
    container_name: gateway
    depends_on:
      - springboot-eureka-server
      - springboot-userservice
      - springboot-favoriteservice
    expose:
      - 9090
    ports:
      - 9090:9090
    environment:
      eureka.client.serviceUrl.defaultZone: http://springboot-eureka-server:8761/eureka

  springboot-favoriteservice:
    image: springboot-favoriteservice:1.0
    container_name: favoriteservice
    depends_on:
      - springboot-eureka-server
      - favoriteservicedb
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      eureka.client.serviceUrl.defaultZone: http://springboot-eureka-server:8761/eureka
volumes:
  favoriteservicedata:
  userservice-mysql-data: