version: "3"

services:
  #RABBITMQ SERVICE FOR SERVICE SERVICE AND RECOMMENDED SERVICE
  rabbitmqservice:
    image: rabbitmq:3.9-management
    container_name: rabbitmqservice
    ports:
      - 5673:5672
      - 15673:15672
    expose:
      - 5673
      - 15673
  #MONGODB SEARCH SERVICE
  mongodbsearchservice:
    image: mongo:latest
    container_name: mongodbsearchservice
    ports:
      - 27017:27017
    volumes:
      - mongodbsearchdata:/data/db
  #MONGODB RECOMMENDED SERVICE
  mongodbrecommendedservice:
    image: mongo:latest
    container_name: mongodbrecommendedservice
    command: mongod --port 27018
    ports:
      - 27018:27017
    volumes:
      - mongodbrecommendeddata:/data/db
  #MONGODB FAVORITE SERVICE
  mongodbfavoriteservice:
    image: mongo:latest
    container_name: mongodbfavoriteservice
    command: mongod --port 27019
    ports:
      - 27019:27017
    volumes:
      - mongodbfavoritedata:/data/db
  #MYSQL SERVICE
  userservicedb:
    image: mysql:8.0
    container_name: userservicedb
    environment:
      MYSQL_DATABASE: gipher
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - userservice-mysql-data:/var/lib/mysql
      - ./sql/gipher.sql:/docker-entrypoint-initdb.d/gipher.sql
  #EUREKA-SERVER SERVICE
  springboot-eureka-server:
    image: springboot-eureka-server:1.0
    container_name: eurekaserver
    ports:
      - 8761:8761
    environment:
      eureka.instance.hostname: springboot-eureka-server
      eureka.client.serviceUrl.defaultZone: http://springboot-eureka-server:8761/eureka
  #EUREKA-CLIENT USER SERVICE
  springboot-userservice:
    image: springboot-userservice:1.0
    container_name: userservice
    ports:
      - 9999:9999
    expose:
      - 9999
    environment:
      spring.datasource.url: jdbc:mysql://userservicedb:3306/gipher?useSSL=false&allowPublicKeyRetrieval=true
      eureka.instance.preferIpAddress: "true"
      eureka.client.registerWithEureka: "true"
      eureka.client.fetchRegistry: "true"
      eureka.client.serviceUrl.defaultZone: http://springboot-eureka-server:8761/eureka
    depends_on:
      - userservicedb
  # EUREKA-CLIENT GATEWAY SERVICE
  springboot-spring-cloud-gateway:
    image: springboot-spring-cloud-gateway:1.0
    container_name: gateway
    depends_on:
      - springboot-eureka-server
      - springboot-userservice
      - springboot-favoriteservice
      - springboot-searchservice
      - springboot-recommendedservice
    expose:
      - 9090
    ports:
      - 9090:9090
    environment:
      eureka.instance.preferIpAddress: "true"
      eureka.client.registerWithEureka: "true"
      eureka.client.fetchRegistry: "true"
      eureka.client.serviceUrl.defaultZone: http://springboot-eureka-server:8761/eureka
  #EUREKA-CLIENT FAVORITE SERVICE
  springboot-favoriteservice:
    image: springboot-favoriteservice:1.0
    container_name: favoriteservice
    depends_on:
      - springboot-eureka-server
      - mongodbfavoriteservice
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      spring.data.mongodb.host: mongodbfavoriteservice
      eureka.instance.preferIpAddress: "true"
      eureka.client.registerWithEureka: "true"
      eureka.client.fetchRegistry: "true"
      eureka.client.serviceUrl.defaultZone: http://springboot-eureka-server:8761/eureka
  #EUREKA-CLIENT SEARCH SERVICE
  springboot-searchservice:
    image: springboot-searchservice:1.0
    container_name: searchservice
    depends_on:
      - springboot-eureka-server
      - mongodbsearchservice
      - rabbitmqservice
    ports:
      - 8082:8082
    expose:
      - 8082
    environment:
      spring.data.mongodb.host: mongodbsearchservice
      eureka.instance.preferIpAddress: "true"
      eureka.client.registerWithEureka: "true"
      eureka.client.fetchRegistry: "true"
      eureka.client.serviceUrl.defaultZone: http://springboot-eureka-server:8761/eureka
  #EUREKA-CLIENT RECOMMENDED SERVICE
  springboot-recommendedservice:
    image: springboot-recommendedservice:1.0
    container_name: recommendedservice
    depends_on:
      - springboot-eureka-server
      - mongodbrecommendedservice
      - rabbitmqservice
    ports:
      - 9095:9095
    expose:
      - 9095
    environment:
      spring.data.mongodb.host: mongodbrecommendedservice
      eureka.instance.preferIpAddress: "true"
      eureka.client.registerWithEureka: "true"
      eureka.client.fetchRegistry: "true"
      eureka.client.serviceUrl.defaultZone: http://springboot-eureka-server:8761/eureka
  #ANGULAR Container
  angular-gipher-frontend:
    build: ./webapp/gipher
    ports:
      - 4200:4200
    volumes:
      - "/webapp/gipher/app/node_modules"
      - ".:/webapp/gipher/app"
volumes:
  mongodbrecommendeddata:
  mongodbsearchdata:
  mongodbfavoritedata:
  userservice-mysql-data: