app:
  message: Message sent to the RabbitMQ queue Successfully
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
    exchange: userexchange
    queue: userqueue
    routingkey: userroutingkey